### ISSUE TITLE
[Feature Request] Windows 10 Support

### ISSUE THREAD

**Issue by YT-Advanced** [creative-builds/WSA-Magisk#16]
### Is your feature request related to a problem?

In Github, we have a dll patch to install WSA in Windows 10. Here is the repos of this patch: 
https://github.com/cinit/WSAPatch

### Describe the solution you'd like

So how about if you update the install.ps1 file to check the Windows version. If the version is 10, copy and paste modifided file to WSA folder then install it.
And can you also add option in Custom Build for people to choose the version for build. Thanks

**Comment by YT-Advanced** [comment]
Support on my own build:
https://github.com/YT-Advanced/WSA-Script

**Comment by rabilrbl** [comment]
Hey @YT-Advanced 

In case you didn't know, this repository is a fork of https://github.com/LSPosed/MagiskOnWSALocal

Please create this issue in the upstream repository.

Thanks
