### ISSUE TITLE
upstream changes causes github actions to fail

### ISSUE THREAD

**Issue by kevin01523** [creative-builds/WSA-Magisk#19]
### Steps to reproduce

build manually or try to merge sync from upstream

### Expected behaviour

no errors and github actions to work flawlessly

### Actual behaviour

theres an upstream changes into the scripts/build.sh and spellcheck workflow which causes the Sync with upstream
and building to fail with github actions

i recommend fixing some codes in accorfance to 
https://www.shellcheck.net/wiki/SC2086
https://www.shellcheck.net/wiki/SC2116

like this line on 844 , 35 on  scripts/build.sh

from
`echo "artifact=$(echo "$artifact_name")" >> $GITHUB_OUTPUT`
to
`echo "artifact=$artifact_name" >> "$GITHUB_OUTPUT"`

this change seems to fix the issue for merging 

from
  `echo "changes=$(git diff --name-only HEAD origin/main)" >> $GITHUB_OUTPUT`
to

`echo "changes=$(git diff --name-only HEAD origin/main | tr '\n' ' ' )" >> "$GITHUB_OUTPUT"`

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal

f29774d147c6ab89652ef6e698589d56ec3bcf5e

### Linux distribution info/Linux

github actions default

### Windows version/Windows

10.0.22621.1344

### Build Parameters

n/a

### Version requirement

- [X] I am using latest commit of MagiskOnWSALocal commit

### Logs

<details>

```
Run git diff --name-only HEAD origin/main
.github/workflows/shellcheck.yml
scripts/build.sh
scripts/generateGappsLink.py
scripts/generateKernelSULink.py
scripts/getWSAMainVersion.py
scripts/install_deps.sh
scripts/run.sh
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'scripts/build.sh'
```
</details>

**Comment by rabilrbl** [comment]
Thanks.
The issue has been resolved.
