### ISSUE TITLE
[Bug] Remove 'Removed' in asset title.

### ISSUE THREAD

**Issue by fillwithjoy1** [creative-builds/WSA-Magisk#21]
### Steps to reproduce

![image](https://github.com/creative-builds/WSA-Magisk/assets/29514446/00432480-f4cf-430d-ab86-a58d5783c136)
All the assets contain Removed at the end which can be confusing

### Expected behaviour

Remove the 'Removed' at the end, (if possible)

### Actual behaviour

Removed exists...

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal

c9f2a8d3f4432ba50b52d5ad1d2bca5c9399ad95

### Linux distribution info/Linux

None

### Windows version/Windows

No need

### Build Parameters

No need

### Version requirement

- [X] I am using latest commit of MagiskOnWSALocal commit

### Logs

No need

**Comment by rabilrbl** [comment]
In case you didn't realize, this repo is a fork from https://github.com/LSPosed/MagiskOnWSALocal 

sure I can push a hack to to eliminate `Removed`, but it is unnecessary and definitely not a bug.
