### ISSUE TITLE
[Feature Request] Add a non-google play services version

### ISSUE THREAD

**Issue by fillwithjoy1** [creative-builds/WSA-Magisk#4]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I'm wanting to test out the Subsystem for Android without the need of Google Play Services, but containing Magisk.

### Describe the solution you'd like/描述你想要的解决方案

The releases section should contain a attachment that is just magisk only and no mind-the-gapps

**Comment by rabilrbl** [comment]
@fillwithjoy1  Thanks for the suggestion! It has been added

**Comment by Rwadxvv** [comment]
> ### Is your feature request related to a problem?/你的请求是否与某个问题相关？
> 
> I'm wanting to test out the Subsystem for Android without the need of Google Play Services, but containing Magisk.
> 
> ### Describe the solution you'd like/描述你想要的解决方案
> 
> The releases section should contain a attachment that is just magisk only and no mind-the-gapps
> 
> ### Additional context/其他信息
> 
> _No response_

2f42e0fdf76de61e54ca3749c72ebfe53586724c
