### ISSUE TITLE
Sorry for the latency. LGTM. These two comments are just nitpicks, please feel free to submit without waiting me.

### ISSUE THREAD

**Issue by Rwadxvv** [creative-builds/WSA-Magisk#9]
https://github.com/creative-builds/WSA-Magisk/commit/7d2cca6f15b3fd9edca4d67e9cc0f523e4ed2998

**Comment by Rwadxvv** [comment]
> https://github.com/creative-builds/WSA-Magisk/commit/7d2cca6f15b3fd9edca4d67e9cc0f523e4ed2998

**Comment by rabilrbl** [comment]
what !?
Describe your problem first
Put appropriate title and description.
